"""Task：可调度的最小工作单元。

Scheduler 只认识 Task，它不知道什么是 Agent、什么是 Step（E-12）。

E-11  Task 必须能溯源到 step_id（一个 Step 可对应多个 Task）
E-19  Task : Execution = 1 : 1（重跑必须新建 Task）
X-2   Kernel 不认识 Goal / Decision，只认识 Task

注意：**Idempotency Key 不在 Task 上**，它挂在 Execution（= execution_id，跨 Attempt 稳定）。
"""
from __future__ import annotations

from dataclasses import dataclass, field
from datetime import timedelta
from enum import Enum
from typing import Any, Mapping

from ..errors import InvariantViolation
from ..ids import new_task_id
from .retry import RetryPolicy


class TaskType(str, Enum):
    """所有执行形态共用一套 Kernel，因此**不再有** ToolExecution / TaskExecution / LLMExecution。"""

    LLM_CALL = "llm_call"
    TOOL_CALL = "tool_call"
    RETRIEVAL = "retrieval"
    SKILL = "skill"
    AGENT_DELEGATION = "agent_delegation"
    HUMAN_APPROVAL = "human_approval"
    WORKFLOW_NODE = "workflow_node"
    CODE_EXECUTION = "code_execution"


class ExecutorType(str, Enum):
    NATIVE = "native"
    MCP = "mcp"
    HTTP = "http"
    AGENT_RUNTIME = "agent_runtime"
    WORKFLOW = "workflow"


@dataclass(frozen=True)
class ResourceReq:
    cpu_millis: int = 100
    memory_mb: int = 256
    gpu: int = 0
    labels: tuple[str, ...] = ()


@dataclass(frozen=True)
class Task:
    task_id: str = field(default_factory=new_task_id)
    run_id: str = ""
    step_id: str = ""                       # E-11
    task_type: TaskType = TaskType.TOOL_CALL
    executor_type: ExecutorType = ExecutorType.NATIVE
    payload: Mapping[str, Any] = field(default_factory=dict)
    priority: int = 0
    resource_requirement: ResourceReq = field(default_factory=ResourceReq)
    retry_policy: RetryPolicy = field(default_factory=RetryPolicy)
    timeout: timedelta = timedelta(seconds=60)
    tenant_id: str | None = None
    version: int = 1

    def __post_init__(self) -> None:
        if not self.run_id:
            raise InvariantViolation("Task.run_id is required")
        if not self.step_id:
            raise InvariantViolation("E-11: Task.step_id is required (traceability to Step)")
        if not self.task_id.startswith("task_"):
            raise InvariantViolation("Task.task_id must be generated by ids.new_task_id()")
        if not isinstance(self.task_type, TaskType):
            raise InvariantViolation(f"unknown task_type: {self.task_type!r}")
        if not isinstance(self.executor_type, ExecutorType):
            raise InvariantViolation(f"unknown executor_type: {self.executor_type!r}")
        if self.timeout <= timedelta(0):
            raise InvariantViolation("Task.timeout must be positive")
        object.__setattr__(self, "payload", dict(self.payload))
